# Generated by Django 5.1.1 on 2024-09-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_user_user_compte_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_login',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_mail',
            field=models.TextField(unique=True),
        ),
    ]
