# Generated by Django 5.1.1 on 2024-12-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='agility',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='chance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='charisma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='endurance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='life_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='magic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='strength',
            field=models.IntegerField(default=0),
        ),
    ]
