# Generated by Django 5.1.1 on 2024-12-15 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_hero_agility_hero_attack_hero_chance_hero_charisma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='agility',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='chance',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='charisma',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='defense',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='endurance',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='life_point',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='magic',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='strength',
        ),
    ]
